### ISSUE TITLE
ZeroClipboard.setText() fails when not linked to a DOM element

### ISSUE THREAD

**Issue by ghost** [zeroclipboard/zeroclipboard#158]
If I am trying to set the clipboard text manually using `setText()`, I have no need to link to a DOM element.  I want to set the clipboard text on my own response to a button click.

Here's some HTML:

``` html
<input type="text" id="Input1" />
<button class="btn" type="button" id="Copy1">Copy Input #1</button>
```

The following code fails to copy the data to the clipboard.

``` javascript
$(document).ready(function () {
  ZeroClipboard.setDefaults({
    moviePath: '/Scripts/ZeroClipboard.swf'
  });

  var clip1 = new ZeroClipboard();

  $("#Copy1").click(function () {
    var data = $("#Input1").val();
    clip1.setText(data);
  });
});
```

This is using Internet Explorer 10 on Windows 8.

**Comment by khudabuxbaloch** [comment]
Hi friends 
i am facing issue in following code (code image is attached) , i take following example from below link , issues is that event is not firing mean link is not click able when ever i am click on link nothing is happening, i am unable to get why this is happening it may be flash player or browser issues or version issues may be but i could not get can any one help please...
http://www.steamdev.com/zclip/
![code-zeroclipboard](https://cloud.githubusercontent.com/assets/9588889/6056583/b543f8c8-ad34-11e4-83c0-9750282a33e3.png)

**Comment by JamesMGreene** [comment]
@khudabuxbaloch: We do not support zClip (no one does anymore, AFAIK). However, you could try a more modern adaptation of it ([terinjokes/zClip](https://github.com/terinjokes/zClip/)) or perhaps try our alternative offering ([zeroclipboard/jquery.zeroclipboard](https://github.com/zeroclipboard/jquery.zeroclipboard/)).
