### ISSUE TITLE
ZeroClipboard doesn't work in Chrome when I upgrade Flash Player to 11.8.800.97

### ISSUE THREAD

**Issue by ghost** [zeroclipboard/zeroclipboard#217]
when I upgrade flash player to 11.8.800.97 , I found "ZeroClipboard " can't work well in chrome.
And the case in "http://zeroclipboard.github.io/ZeroClipboard/#demo", it doesn't work well either.
can you check it. 
Thank you very much.

**Comment by Marshevskyy** [comment]
hey guys. looks like ZeroClipboard doesn't work in Chrome again. Can you confirmed that?
