### ISSUE TITLE
ZeroClipboard non functional on IE after reload

### ISSUE THREAD

**Issue by andrewkerr9000** [zeroclipboard/zeroclipboard#23]
To reproduce:
- Go to test page http://jonrohan.github.com/ZeroClipboard/#demo using IE
- Change copy text and use copy button to observe it working
- Reload the page
- Change copy text and use copy button - no debug console output and new text is not in clipboard

If the page is refreshed bypassing cache then ZeroClipboard works again - until it is refreshed from cache.

Tested on IE9 and IE7. No JS errors are thrown.

**Comment by frabcus** [comment]
This is a bit sad :(

Does it happen on later versions of IE too? Wondering about making it conditional, as it is an extra load time on all of our pages.

**Comment by JamesMGreene** [comment]
@frabcus: You should try it again with `v2.2.0` and let us know! If _anything_ is going to fix it, my changes in d1a504f1b1ca2b20c80355e467058e27f25ae0f8 (included in `v2.2.0`) should do the trick.

**Comment by pwaller** [comment]
@JamesMGreene @frabcus and I tried v2.2.0 but it didn't seem to fix it.

**Comment by JamesMGreene** [comment]
@pwaller: Bummer. :cry:
