### ISSUE TITLE
Zeroclipboard doesn't work in Firefox Bootstrap modal

### ISSUE THREAD

**Issue by akashSE** [zeroclipboard/zeroclipboard#460]
It works just fine on the main window, however, the functionality doesn't work inside a modal.

Any ideas? I realize there is a problem with modals in IE but I'm having this problem in Firefox and can't seem to find any help.

I have this inside my template which is used in when the modal opens.

![capture](https://cloud.githubusercontent.com/assets/2330963/3566736/b824bf5e-0b00-11e4-8e4d-7b5875c54cc0.JPG)

The following code is found in my javascript script
var client = new ZeroClipboard( $('.clip_button') );

**Comment by saifelse** [comment]
I would like to confirm that Firefox 38 has the same bug as IE causing the keyboard to lock up in all tabs in that window (while Firefox 36 does not have this issue), and that both workarounds seem to do the trick.

I've filed the bug in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1177366

**Comment by odroz** [comment]
Hi I confirm as well that this bug still occurs in FireFox 39 and 40. Please vote for saifeise's bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1177366

Thanks

**Comment by odroz** [comment]
Hi @JamesMGreene I'm a bit confused. Where should the workaround (A or B) be inserted? Is that modifying bootstrap.js? Or Zeroclipboard.js? My angularJS controller?
I'm using ZeroClipboard with ng-clip. I'm really not familiar with JQuery. 
Thanks a lot!
