### ISSUE TITLE
Data URI base64 encoded .SWF file support?

### ISSUE THREAD

**Issue by iglvzx** [zeroclipboard/zeroclipboard#485]
Is it possible to load the .SWF file using data URI Base64 encoding instead of using a URL? The goal being to load the Flash object without having to make an external HTTP request.

**Comment by skylerspark** [comment]
I encoded an Swf, Tried the Data:ShockwaveFlashObject/swf;base64,DATAHASHHERE
and that didnt work, I tried swf on its own and a few other methods, but other then that... well it doesnt want to register it as ANYTHING. it just says that it doesnt exist

**Comment by skylerspark** [comment]
if anyone has an uptodate way of doing this to an SWF game file, and allow it to run successfully on Chrome, I would greatly Apreciatte it.
