### ISSUE TITLE
Bug with removing the class name zeroclipboard-is-hover on  IE11

### ISSUE THREAD

**Issue by ravitbar** [zeroclipboard/zeroclipboard#501]
On IE11 the class is added properly but does not remove when the mouse leaves the element.

**Comment by JamesMGreene** [comment]
@ravitbar: Did you ever get a chance to retest this with `v2.2.0`? If so, please let us know the results. Thanks!

**Comment by JamesMGreene** [comment]
Closing as this appears to work in `v2.2.0` on IE11 when I test it on the demo page (http://zeroclipboard.org/).
