### ISSUE TITLE
ZeroClipboard doesn't work in JsFiddle

### ISSUE THREAD

**Issue by loganvolkers** [zeroclipboard/zeroclipboard#511]
We've been using JsFiddle for a long time and recently it seems to have stopped working when embedded in a JsFiddle iframe.

We're naturally curious to see why this has regressed, so we made a test case.

- JsFiddle test case (doesn't work) - http://jsfiddle.net/loganvolkers/koa04mju/
- Without an iframe (works) - http://fiddle.jshell.net/loganvolkers/koa04mju/show/

*In an iframe* it appears that flash has been disabled by JsFiddle:
```json
{"type":"error",
"name":"flash-disabled",
"target":null,
"relatedTarget":null,
"currentTarget":null,
"timeStamp":1415318935611,
"message":"Flash is disabled or not installed",
"minimumVersion":"11.0.0"}
```

*Directly visiting the page* seems to work just fine

```json
{"type":"ready",
"target":null,
"relatedTarget":null,
"timeStamp":1415319109675,
"message":"Flash communication is established",
"version":"15.0.0"}
```

**Comment by JamesMGreene** [comment]
I've done all I can for this issue now. The sandboxing is a huge PITA but it's nothing that we can expect to go away as it adds very legitimate value for the various playground sites that employ it.

**Comment by JamesMGreene** [comment]
P.S. Link to documentation on "starter snippets": [docs/instructions.md#starter-snippets-for-playground-sites](https://github.com/zeroclipboard/zeroclipboard/blob/f0263698a4123376bb46bbd814fd968f48b9def1/docs/instructions.md#starter-snippets-for-playground-sites)
