### ISSUE TITLE
Blue Border around clipped element after click

### ISSUE THREAD

**Issue by jesseclark** [zeroclipboard/zeroclipboard#518]
After clicking a clipped element a light blue border appears around the clipped element. It stays that way until I click any other element on the page. 

I don't have anything in my css that should be causing that.

I have tried adding:
```
#global-zeroclipboard-flash-bridg3,
#global-zeroclipboard-html-bridge,
.zeroclipboard-is-hover,
.zeroclipboard-is-active,
.global-zeroclipboard-container {
	border: none !important;
}
```
to my css with no effect.

I would appreciate any suggestions.

Update: The blue border was displayed when the clipped element was an anchor tag. When I changed the clipped element to an image tag it no longer occurred.

**Comment by thenitai** [comment]
I was able to workaround this with:
```
.copy_button:focus {
  outline: 0;
}
