### ISSUE TITLE
Object doesn't support property or method 'map' in ZeroClipboard.js

### ISSUE THREAD

**Issue by tvsrkp** [zeroclipboard/zeroclipboard#539]
Hi,

When I am trying to copy text to clipboard from IE I am getting the following exception in ZeroClipboard.js..
Object doesn't support property or method 'map'..
My code looks like this...

<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

      <script type="text/javascript" src="JQuery/jquery-1.3.2.js" />
      <script type="text/javascript" src="ZeroClipboard/ZeroClipboard.js" />
       <script type="text/javascript">
        if(!window.location.origin) {
        	window.location.origin = window.location.protocol + "//" + window.location.host;
        }
        $(document).ready(function(){
        	try{
        		var clip = new ZeroClipboard($('.clipcopy'));
        
        	clip.on("copy", function(event) {
        	var clipData = $(event.target).attr('data-clipboard-text');
        	clipData = window.location.origin + clipData;
        	event.clipboardData.setData("text/plain", clipData);
        	});
        	}catch(err)
        	{
        		alert(err.message);
        	}
        });

**Comment by JamesMGreene** [comment]
Please see [README.md#support](https://github.com/zeroclipboard/zeroclipboard/blob/master/README.md#support)

**Comment by JamesMGreene** [comment]
P.S. Even if you need to support "oldIE", please consider upgrading your version of jQuery to the latest `1.x` version... your version is 4 years and 11 months old. :weary:
