### ISSUE TITLE
the swfPath can be not based on the location  of the executing JavaScript file?

### ISSUE THREAD

**Issue by xuyongtao** [zeroclipboard/zeroclipboard#540]
the swfpath can be based on the path of ZeroClipboard.js instead the location of the executing JavaScript file?

**Comment by xuyongtao** [comment]
the method _swfPath() : 
```
 if (_document.readyState === "loading") {

        jsPath = scripts[scripts.length - 1].src;
        console.log(jsPath)
  } 
if the last script is <script>alert(1)</script> ; the var jsPath is empty, so the var swfPath is wrong

```

**Comment by JamesMGreene** [comment]
Can you provide an example JSBin that reproduces the problem?

Also, the path detection is highly dependent on browser, so what browser and version are you running into this problem on?

You can always set the SWF path manually (`ZeroClipboard.config({ swfPath: "path/to.swf" });`), we just make our best effort to set it for you.

**Comment by xuyongtao** [comment]
thank you !    ZeroClipboard.config({ swfPath: "path/to.swf" })  is what i need.

**Comment by JamesMGreene** [comment]
That's good. :+1:

If you get a chance, though, I would still love answers to my questions above so I can try to arrive at a more accurate default path determination, if at all possible. It's unfortunately stupid-hard to get accurate and consistent results cross-browser but I'd like to make it as close as possible!

**Comment by JamesMGreene** [comment]
I made a [simple JSBin test page](http://jsbin.com/yahuja/2/) that seems _similar_ to what you described but I'm having trouble reproducing the issue on any browsers that ZeroClipboard supports. I used BrowserStack to assess all of them except for Chrome 39 (which I ran on my local machine).

| Browser | Browser `v` | OS | OS `v` | Result | 
|-------------|----------------:|------|----------:|----------|
| IE | 11.0 | Windows | 8.1 | :+1: |
| IE | 11.0 | Windows | 7 | :+1: |
| IE | 10.0 | Windows | 8 | :+1: |
| IE | 10.0 | Windows | 7 | :+1: |
| IE | 9.0 | Windows | 7 | :+1: |
| Firefox | 30.0 | Windows | 7 | :+1: |
| Firefox | 30.0 | OS X | 10.9 | :+1: |
| Chrome | 39.0 | OS X | 10.9 | :+1: |
| Chrome | 36.0 | Windows | 7 | :+1: |
| Chrome | 36.0 | OS X | 10.9 | :+1: |
| Safari | 8.0 | OS X | 10.10 | :+1: |
| Safari | 7.0 | OS X |10.9 | :+1: |
| Safari | 6.1 | OS X | 10.8 | :+1: |
| Safari | 6.0 | OS X | 10.7 | :+1: |
| Safari | 5.1 | OS X | 10.6 | :+1: |
| Safari | 5.1 | Windows | 7 | :+1: |
| Opera | 12.16 | Windows | 7 | :+1: |
| Opera | 12.15 | OS X | 10.9 | :+1: |

**Comment by xuyongtao** [comment]
thank you,must i make a mistake. i will test again

**Comment by xuyongtao** [comment]
why not insert the flash container(id is global-zeroclipboard-html-bridge)  into the trigger element $('.J-copy-phone') , because some events which are bind to the parent element of the trigger element will trigger,like event mouseout.

new ZeroClipboard($('.J-copy-phone'));

**Comment by JamesMGreene** [comment]
Check out the detailed explanation and potential workarounds in https://github.com/zeroclipboard/zeroclipboard/issues/536.
