### ISSUE TITLE
ZeroClipboard breaks IE8 when included

### ISSUE THREAD

**Issue by asafbrukarz** [zeroclipboard/zeroclipboard#546]
Before I get shouted down and told "We don't support IE8 since v2.0.2", let me explain my situation first.

In our application, I'm happy to let IE8 users suffer a severely degraded experience. However, simply including the ZeroClipboard script on the page (without calling any functions), breaks the scripts (as `_defineProperty` is not supported). 

In our Rails app, assets are bundled together, so a failure in one script will fail the entire script. The effect for us is that IE8 users have NO Javascript.

While it's fine to remove support for IE8 and below, my preference would be to avoid breaking the browser if someone does include the script for IE8 users.

Some options I'd like to put forward:
- If the user is running an unsupported browser, do nothing; or
- Wrap function calls like `_defineProperty` in a try/catch block; or
- Delay global function calls until a ZeroClipboard object is initialised. This would at least allow including the script in an unsupported browser and would only fail once `new ZeroClipboard` was called.

**Comment by JamesMGreene** [comment]
Point well taken. I'll have to do a review of all the ES5.1 and DOM Level 2+ features we're leveraging to see what makes the most sense.

Ideally, I think the API should _appear_ usable but be emitting a new `error` event, e.g. `error[name = "browser-unsupported"]`.

**Comment by asafbrukarz** [comment]
I have patched my local version of ZeroClipboard and can confirm that changing:

```
  _defineProperty(ZeroClipboard, "version", {
    value: "2.2.0",
    writable: false,
    configurable: true,
    enumerable: true
  });
```

to 

```
  ZeroClipboard.version = "2.2.0"
```

fixes the issue and avoid breaking IE8. To test for IE8 before calling the ZeroClipboard constructor, I have simply used `if (document.addEventListener === undefined) { return; }`

**Comment by JamesMGreene** [comment]
The fix will be forthcoming in the next release. Thanks!
