### ISSUE TITLE
'Undefined' when copying Ajax result to clipboard

### ISSUE THREAD

**Issue by bdetail** [zeroclipboard/zeroclipboard#550]
Firstly, I want to say thanks for the great library. 

I'm trying to copy an Ajax result to clipboard.  I'm getting 'undefined' when I click the button first time but when I click it a second time, it copies the Ajax result correctly. It seems I always have to click the button twice for it to work correctly. 

Here's a very basic working example so you can see what's happening http://goo.gl/oNKFyL

I'd be grateful if someone could point me in the right direction.

Windows 8.1
Chrome 40.0.2214.115 m
Is Flash enabled? true
Flash version? 16.0.0
Using Pepper Flash? true
Using ActiveX? false
ZeroClipboard v2.2.0

**Comment by JamesMGreene** [comment]
**From [docs/instructions.md#synchronicity-required-during-copy](https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/instructions.md#synchronicity-required-during-copy):**

> ### Synchronicity Required During `copy`

> If a handler of `copy` event intends to modify the pending data for clipboard injection, it _MUST_ operate synchronously in order to maintain the temporarily elevated permissions granted by the user's `click` event. The most common "gotcha" for this restriction is if someone wants to make an asynchronous XMLHttpRequest in response to the `copy` event to get the data to inject &mdash; this will not work. You must make it a _synchronous_ XMLHttpRequest instead, or do the work in advance before the `copy` event is fired.

**Comment by bdetail** [comment]
Finally got it working. Here's the code for others:

```javascript
var client = new ZeroClipboard( $('#btn1, #btn2, #btn3') );	
ZeroClipboard.config( { swfPath: "/js/ZeroClipboard.swf" } );				

client.on( 'ready', function(event) {	
	client.on( 'copy', function(event) {		
		var bid = event.target.id; //button id			
		$.ajax({
			type: "GET",
			url: "response.php?bid="+bid,
			async: false,
		    success: function(data) {
			   console.log('Ajax result received: ' + data);
			   event.clipboardData.setData('text/plain', data);	
		   }
		});
	});	
	client.on( 'aftercopy', function(event) {					
		console.log('Copied text to clipboard: ' + event.data['text/plain']);
	});	
});	
```

Tá fáilte romhaibh.
