### ISSUE TITLE
First time not work After ajax request 

### ISSUE THREAD

**Issue by junaidcs** [zeroclipboard/zeroclipboard#553]
Hi there!

I'm having issue, when i click first time, it send request with Ajax, then i wanna copy the ajax response.First time it don't copy i need to click again. Here is my code snippet.
```javascript
<script src="/zero_clip/ZeroClipboard.js"></script>
$(document).ready(function() {
  var client = new ZeroClipboard( $("#copyLink") );
  $("#copyLink").click(function () {
    $.ajax({
      url: "/controller/method/",
      method: "GET"
    }).success(function (res,status) {
      client.setData('text/plain', res.url);
    });
  });  
});
```

It works fine this this way

```javascript
<script src="/zero_clip/ZeroClipboard.js"></script>
$(document).ready(function() {
  var client = new ZeroClipboard( $("#copyLink") );
  $("#copyLink").click(function () {
    client.setData('text/plain', 'Some text');
  });  
});
```
Thanks

**Comment by JamesMGreene** [comment]
**From [docs/instructions.md#synchronicity-required-during-copy](https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/instructions.md#synchronicity-required-during-copy):**

> ### Synchronicity Required During `copy`

> If a handler of `copy` event intends to modify the pending data for clipboard injection, it _MUST_ operate synchronously in order to maintain the temporarily elevated permissions granted by the user's `click` event. The most common "gotcha" for this restriction is if someone wants to make an asynchronous XMLHttpRequest in response to the `copy` event to get the data to inject &mdash; this will not work. You must make it a _synchronous_ XMLHttpRequest instead, or do the work in advance before the `copy` event is fired.
