### ISSUE TITLE
Blank page after loading script

### ISSUE THREAD

**Issue by JoseRoman** [zeroclipboard/zeroclipboard#554]
After I include the ZeroClipboard.js file in html document the page doesn't show anything.

     <script src="public/javascripts/ZeroClipboard.js"</script> 

__Using Node.js with Express and no error in console__

**Comment by JamesMGreene** [comment]
Huh, I've never heard of that one before.  Personally, I doubt ZeroClipboard is really a factor but I could be mistaken.

**Questions:**
 - [ ] And if you remove the script, then the page renders fine and shows something?
 - [ ] What version of ZeroClipboard are you using?
 - [ ] What browser (and version) are you using?
 - [ ] Do you have both the "ZeroClipboard.js" and "ZeroClipboard.swf" files in that same directory?
 - [ ] Can you provide an example to repro the issues (either a hosted page, a JSBin, or just an easily runnable GitHub repo)?

**Comment by JoseRoman** [comment]
1. Yes, if I remove the script the page renders fine.
2. Using v2.2.0 of ZeroClipboard
3. Chrome 41.0.2272.76
4. Both files (JS and SWF) are in the same directory.
5. Not at the moment.

**Comment by JoseRoman** [comment]
Solved this issue by including ZeroClipboard file outside main layout (Using handlebars as template engine).

**Comment by JamesMGreene** [comment]
> Solved this issue by including ZeroClipboard file outside main layout (Using handlebars as template engine).

I'm glad you got this worked out, though I'm curious if you can explain your change a bit further for my own curiosity. If not, no worries! :+1:
