### ISSUE TITLE
Lengthy text is not copied in google chrome

### ISSUE THREAD

**Issue by dewitt-li** [zeroclipboard/zeroclipboard#557]
I have a requirement to copy a long text to clipboard, it's not working in google chrome, it is working in Firefox though. I tried the same big text with the demo on http://zeroclipboard.org/. The text used is "abcdefghijklmnopqistuvwxyz" repeated 110592 times. It copies fine in Firefox, but failed in chrome.

**Comment by JamesMGreene** [comment]
Duplicate of #529, I guess. :sad:
