### ISSUE TITLE
Clipboard Content-Type - image/gif;charset=UTF-8

### ISSUE THREAD

**Issue by tejakandukuri** [zeroclipboard/zeroclipboard#558]
I Want to clipboard the response of AJAX  which is of content-type image/gif;charset=UTF-8. 
Example : GIF89a����,;

Please help me, how can I achieve this.

**Comment by JamesMGreene** [comment]
You _may_ be able to transfer an image if it is encoded as a Data URI or Blob URL in the "text/html" segment of the clipboard but I'm not positive (that's never been a use case for me, personally).

ZeroClipboard unfortunately has to rely on Flash until browser vendors get around to solidifying [or, in most cases, even _starting_ to implement] the HTML Clipboard API, and Flash can only support "text/plain", "text/html", and "application/rtf".

**Comment by JamesMGreene** [comment]
I'm labeling this as a "wontfix" but also "HTML Clipboard API" so that we can consider revisiting it once the HTML Clipboard API earns some real browser implementations for copy actions.
