### ISSUE TITLE
I cannot use data-clipboard-target like the example

### ISSUE THREAD

**Issue by efkan** [zeroclipboard/zeroclipboard#562]
Hello,

I've been trying to implement codes second item from the below address
https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/instructions.md#text-to-copy

The below example looks like very nice. However I spent 8 hours and I couldn't be successful.
http://zeroclipboard.org/#demo

Actually I need to use ZeroClipboard for two different elements. I can accomplish if I use for just one elements. Otherwise every time second constructed element's copy operation works.

    <body>

          <div class="form-group">
             <label for="client_id" class="control-label">Client ID:</label>
             <button id="copy_id" data-clipboard-target="client_id">Copy ID</button>
             <input id="client_id" class="form-control" >
         </div>        
          <div class="form-group">
             <label for="client_id" class="control-label">Client ID:</label>
             <button id="copy_secret" data-clipboard-target="client_secret">Copy Secret</button>
             <input id="client_secret" class="form-control" >
         </div>     

         <script type="text/javascript" src="/js/ZeroClipboard.js"></script>
                 
         <script>
                    // I think I should write some codes here but which codes?
         </script>

    </body>

**Comment by efkan** [comment]
I had to use an alternate way;

    var client = new ZeroClipboard( $('.clip_button'), {
	      moviePath: "/js/ZeroClipboard.swf"
	    } )

    client.on("copy", function(e) {
    	var clipboard = e.clipboardData;
    	if(e.target.id == "copy_id")
    		clipboard.setData("text/plain", $("#client_id").val())
    	else
    		clipboard.setData("text/plain", $("#client_secret").val())
    })

Thank you all who have worked for this useful tool...

**Comment by JamesMGreene** [comment]
@efkan This should've worked fine and I would like to investigate further if it truly was not. Can you provide me with an otherwise-working JSFiddle/JSBin/CodePen/etc. of your setup?

**Comment by JamesMGreene** [comment]
For your particular case, the following should've been sufficient:

```html
<script>
  // I think I should write some codes here but which codes?
  var client = new ZeroClipboard( $('button[data-clipboard-target]') );
</script>
```
