### ISSUE TITLE
Using swf from cdn causes _setHandCursor to throw error

### ISSUE THREAD

**Issue by christianvoigt** [zeroclipboard/zeroclipboard#570]
Hi, I tried to use the cdn version of ZeroClipboard with an element that has the style `cursor:pointer`. I thought I could use `ZeroClipboard.config( { swfPath: "https://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.swf" } );

But this didn't work. On rollover an error is thrown by `_flashState.bridge.setHandCursor(enabled);`. The error message is: "Uncaught Error: Error: An invalid exception was thrown." After commenting this line out, everything worked as expected (just without the pointer cursor). 

Is this supposed to work? Otherwise this is probably a documentation issue.

**Comment by JamesMGreene** [comment]
Is your page hosted on the `https://` protocol as well?

**Comment by christianvoigt** [comment]
Thanks for the tip, that's it. I changed the link to `ZeroClipboard.config( { swfPath: "//cdn.jsdelivr.net/zeroclipboard/2.2.0/ZeroClipboard.swf" } );` and it works. I think it would be a good idea to mention this in the instructions.

**Comment by JamesMGreene** [comment]
It is: [docs/instructions.md#cross-protocol-limitations](https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/instructions.md#cross-protocol-limitations)

Understandable to miss it, though... there are a LOT of unavoidable configuration/troubleshooting/gotcha points with this type of Flash integration. :+1:

I'm  planning to add another `error` event type in the next minor release to help track down this particular issue, see #532.
