### ISSUE TITLE
Allow for multiple tooltips...

### ISSUE THREAD

**Issue by webfro-gs** [zeroclipboard/zeroclipboard#576]
Please see the following Fiddle **[here][1]**.

I am trying to hover over each div, but allow a tooltip to pop up on each one. However, you'll notice the top button (in the fiddle) has the black tooltip, and the bottom button has the standard browser tooltip. 

How can I accomplish applying this id (myClip) to multiple elements? 

Here's what initiates the ZeroClipboard - 

    <script type="text/javascript">
      var client = new ZeroClipboard( $('.clip_button') );
	  
	  ZeroClipboard.config( { swfPath: "ZeroClipboard.swf" } );

      client.on( 'ready', function(event) {
        // console.log( 'movie is loaded' );

        client.on( 'copy', function(event) {
          event.clipboardData.setData('text/plain', event.target.innerHTML);
        } );

        client.on( 'aftercopy', function(event) {
          console.log('Copied text to clipboard: ' + event.data['text/plain']);
        } );
      } );

      client.on( 'error', function(event) {
        // console.log( 'ZeroClipboard error of type "' + event.name + '": ' + event.message );
        ZeroClipboard.destroy();
      } );
    </script>

Here's the JS for the tooltip - 

    <script type="text/javascript">//Allows tooltip
    	$(function() {
    	  var hex = document.getElementById("hex_rgb");
    	  var client = new ZeroClipboard(hex);
    	  $('#hex_rgb').tooltip();
    	  client.on('ready', function(event) {
    		client.on('copy', function(event) {
    		  event.clipboardData.setData('text/plain', event.target.innerHTML);
    		});
    		client.on('aftercopy', function(event) {
    		  $('.tooltip .tooltip-inner').text('Color Copied!');
    		});
    	  });
    	})
    </script>

Please don't comment on the functionality of ZeroClipboard. It doesn't seem to function in JSFiddle. I have it working on my site though. 

  [1]: http://jsfiddle.net/webfrogs/5unqapgv/

**Comment by JamesMGreene** [comment]
**Example code:**  http://jsfiddle.net/JamesMGreene/dkmvxnxq/
**Live working demo:** http://fiddle.jshell.net/JamesMGreene/dkmvxnxq/show/

**Basic code, based on the code present in your original JSFiddle:**


```js
$(function () {

    var $clipButtons = $('.clip_button');
    $clipButtons.on('mouseover', function(e) { $(e.target).tooltip(); });
    
    var client = new ZeroClipboard($clipButtons);

    client.on('ready', function (event) {
        console.log( 'movie is loaded' );

        client.on('copy', function (event) {
            event.clipboardData.setData('text/plain', event.target.innerHTML);
        });

        client.on('aftercopy', function (event) {
            $('.tooltip .tooltip-inner').text('Copied!');
        });

    });

    client.on('error', function (event) {
        console.log( 'ZeroClipboard error of type "' + event.name + '": ' + event.message );
        ZeroClipboard.destroy();
    });
});
```

**Comment by JamesMGreene** [comment]
Does this wholly resolve your needs, @webfro-gs?  I'm going to close the issue for now but feel free to reopen it if there is more to work out.

**Comment by webfro-gs** [comment]
Looks good to me James (sorry for the late reply). Thanks.
