### ISSUE TITLE
Copy email signature to clipboard?

### ISSUE THREAD

**Issue by behnampmdg3** [zeroclipboard/zeroclipboard#577]
Hi;

I want to copy and paste"SOMETHING" in any email clients email signature box with the css we
apply to it. Can we copy to clipboard rendered html?can you make it so that the footer is in a copy box.
i.e when you select you just get the content of the box? The client wants me to add a "Copy Email Signature to Clipboard" feature.

< button id="copy-button" data-clipboard-text='<?php echo $copy;?>'>Copy to Clipboard</button> 

Thanks

**Comment by JamesMGreene** [comment]
Can please show us what the value of `$copy` would look like?

Also, do you want to copy that value as plain text (HTML markup) or as rendered HTML?

**Comment by behnampmdg3** [comment]
Hello James;

Yes rendered HTML so users can just copy it in their email signature and links be actual links.

I can make $copy can be something like this (Please ignore white spaces, I just added them so Github doesn't modify the actual text):

< strong style = "color:red">Name: </strong>John Doe<br />
< a h ref = "h ttp://www.website.com">www.website.com</a><br />
< a h ref=“m ailto:obama@whitehouse.gov”>obama@whitehouse.gov</a><br />

Or basically, like this: http://grab.by/HJM4

Thank you

**Comment by JamesMGreene** [comment]
Is the text/rendered HTML displayed on the page in another element?

**Comment by behnampmdg3** [comment]
Not really. I generate it with php. I can do whatever is suitable for the clipboard.

**Comment by behnampmdg3** [comment]
Hi;

Sorry we are a little confused on how to copy the data. We have the item we want to copy rendered on a page that has  the copy button displayed, but currently we are copying the code generated directly from the php that generates the page. Having looked through the docs I cant see how we can copy the outputted html off the rendered page.

**Comment by GordonKiomon** [comment]
hi behnampmdg3, how did you solve it?

**Comment by behnampmdg3** [comment]
Sorry about the mess, but you get the idea...


ob_start();
                            foreach($profile_details as $val =>$row)
                                {
                                    foreach($buttons as $button)
                                        {
                                           if($button == 'last_name')
                                                {
                                                    $last_name_showed = true;
                                                }
                                           if($button == 'company')      
                                                {
                                                    $company_showed = true;
                                                }
                                            if(strlen($row->$button)>0)
                                                {
                                                    $query = $this->db->get_where('content_items', array('card_details_value' => $button));
                                                    $res = $query->result_array();
                                                    $b = str_replace("_", " ", $button);
                                                    if($button!="last_name"){?><p><?php }
                                                        $link = $row->$button;
                                                        $query_link = $this->db->get_where('preview_buttons', array('card_details_column' => $button));
                                                        if($query_link->num_rows()>0)
                                                           {
                                                                $link = $query_link->result_array()[0]['link'];
                                                                $link = "<a href = \"".html_escape($link.$row->$button)."\">".html_escape($row->$button)."</a>";
                                                            }    
                                                        $copy .= $b.": ".$row->$button."\r\n";
                                                        if(in_array($button, $name))
                                                            {
                                                                echo "<strong style = 'color:black'>";
                                                            }
                                                        if(!in_array($button, $headers))
                                                            {
                                                                echo ucfirst($b).": ";
                                                            }   
                                                        echo ucfirst($link);
                                                        if(in_array($button, $name))
                                                            {
                                                                echo "</strong> ";
                                                            }

                                                    if($button!="first_name"){?></p><?php }
                                                    if(strlen($logo)>4 && $logo_show==true && $last_name_showed==true)
                                                        {
                                                            $logo_show = false;?>
                                                        <div class="email-footer-logo ">
                                                            <img class="img-responsive" src="<?php echo $logo;?>" alt="">
                                                        </div>
                                                    <?php }
                                                    if($connect_with_me_show==true && $last_name_showed==true && $company_showed==true)
                                                        {
                                                            echo "<p><a href = \"".$row->full_url."-e"."\">Connect With Me</a></p>";
                                                            $connect_with_me_show = false;
                                                        }   
                                                }
                                            }        
                                    }
                      $copy = ob_get_clean();
                      echo $copy;
                            ?></div>
        <div class="row">
            <div class="col-md-12 text-center margin-bottom-lg">
                <button id="copy-button" class="btn btn-primary"><i class="fa fa-copy"></i> Copy to Clipboard</button>
                <script>
                    $(document).ready(function () {
                        var client = new ZeroClipboard( $("#copy-button") );

                        client.on( "ready", function( readyEvent )
                            {
                                client.on( "aftercopy", function( event )
                                    {
                                        alert("Copied text to clipboard!" );
                                    }
                                );

                                client.on( "copy", function (event) {
                                    var clipboard = event.clipboardData;
                                    clipboard.setData( "text/html", "<?php echo str_replace(array("\"", "\n"), array("'", ""), $copy);?>" );
                                });
                            }
                        );
                    });
                </script>

**Comment by GordonKiomon** [comment]
got it. thanks
