### ISSUE TITLE
Feature detect whether document.execCommand("copy") can be used instead of Flash

### ISSUE THREAD

**Issue by cpeterso** [zeroclipboard/zeroclipboard#580]
The `document.execCommand()` clipboard APIs are available in Firefox 41+, Chrome, Safari, and IE:

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

http://www.quirksmode.org/dom/execCommand.html

**Comment by ehsan** [comment]
In Firefox, you can feature detect this support by calling `document.queryCommandSupported("copy")` (similarly for cut.)

Inside a user event handler, you can also call `document.queryCommandEnabled("copy")` to check whether calling `execCommand("copy")` would succeed.  If you call that function outside of an event handler, it should return false.

**Comment by JamesMGreene** [comment]
I need to do some more exploratory testing but I'm fairly sure that Chrome is the only one that will support this without permissions prompts (IE) or special security config settings (Firefox).

Also, not being able to check `document.queryCommandEnabled("copy")` until the user clicks is unfortunately too late to make that call, so we would have to load the Flash movie anyway to ensure a seamless first copy attempt, even if we can remove it for subsequent attempts. Very frustrating implementation.

**Comment by mzgol** [comment]
It's going to be supported in Firefox by default soon (in 3 releases or so). So hacks will be needed only for IE & Safari (has anyone talked to the Edge team about that?).

**Comment by JamesMGreene** [comment]
@mzgol Thanks for that info! Is there a Bugzilla item or status page we can follow to track the release of this particular Firefox update?

A few folks from the IE team have definitely been involved in the Clipboard API spec discussions. I'm as suming the IE team is heavily linked into the development of Edge, right?

As for Safari, I don't recall seeing anyone from Apple or WebKit involved in spec discussions... which is extra disappointing since iOS is the only major platform on which ZeroClipboard cannot work at all today (due to complete lack of Flash support). :cry:

**Comment by JamesMGreene** [comment]
> As for Safari, I don't recall seeing anyone from Apple or WebKit involved in spec discussions... which is extra disappointing since iOS is the only major platform on which ZeroClipboard cannot work at all today (due to complete lack of Flash support). :cry:

@rniwa Are you aware of anyone at Apple/WebKit  who may be quietly following along with the Clipboard API spec and already implementing it unbeknownst to me?

**Comment by JamesMGreene** [comment]
@rniwa And, if not, any suggestion on how we can get that as at least a medium priority on someone's radar?

**Comment by mzgol** [comment]
> @mzgol Thanks for that info! Is there a Bugzilla item or status page we can follow to track the release of this particular Firefox update?

See https://bugzilla.mozilla.org/show_bug.cgi?id=1012662. It's scheduled for Firefox 41 that's supposed to arrive on 2015-09-22. (via https://wiki.mozilla.org/RapidRelease/Calendar) You can test on Nightly right now & file bugs that surely exist. ;-)

> A few folks from the IE team have definitely been involved in the Clipboard API spec discussions. I'm as suming the IE team is heavily linked into the development of Edge, right?

The former IE team is now the Edge team. The browser changed its name, dropped ActiveX, document modes & *a lot* of similar cruft and now only Edge is going to be developed (maybe with a few exceptions like HSTS coming to IE11). Windows 10 will include both Edge - actively developed, always automatically updated to the latest versions - and IE11 - receiving (mostly) only security fixes.

So, I expect that if the problem exists in IE11 it will never disappear there but in Edge it might.

> As for Safari, I don't recall seeing anyone from Apple or WebKit involved in spec discussions...

We still should reach out to them. But yeah, poor communication between Safari devs & web developers is frustrating.

**Comment by JamesMGreene** [comment]
@mzgol: Granted, Microsoft's primary contact and resident IE text editing export (as I understand it) was @BenjamP, who apparently left Microsoft in March and now works at Amazon. :open_mouth: 

@BenjamP: Is there any particular contact(s) at Microsoft we should ensure remain involved in the Clipboard API spec discussions to keep Microsoft Edge on track in your absence? You will be missed. :disappointed:

**Comment by mzgol** [comment]
@JamesMGreene perhaps @jacobrossi can help. :) Or point to someone who could.

**Comment by JamesMGreene** [comment]
Please shift conversation from here to #171. Thanks!

**Comment by jonrohan** [comment]
Here's what github does to enable copy to clipboard without flash. It's based on useragent sniffing and not feature detection, which is why it's not in ZC yet. https://gist.github.com/jonrohan/81085b119d16cdd7868a

**Comment by dandv** [comment]
@jonrohan: right now, this is implemented on gist.github.com, but not on github.com.

I have IE11 without flash, and don't see the copy buttons for github repo paths, but do see them at the gist link you listed.

**Comment by zenorocha** [comment]
Hey guys, I wrote a [polyfill for document.queryCommandSupported](https://github.com/zenorocha/document.queryCommandSupported).

I didn't want to include it on clipboard.js because we could collaborate on this separately ;)

**Comment by zenorocha** [comment]
@jonrohan thanks for sharing GitHub's implementation. Should Opera 30 be detected as well?

**Comment by jonrohan** [comment]
Hate to say that we don't put a lot of effort into Opera detection. We try to use polyfills when necessary, but it's not a browser that's used enough on our site.

So I would say that as long as it isn't a bunch of extra work or bloats the js, go for it. If it is too much work, then skip it.

**Comment by mzgol** [comment]
@zenorocha I don't think it's a good idea to skip the method in covered
browsers in all versions, someone could disable support and it should
return `false` then. For example for Firefox I'd return `false` if version
< 41 but for 41+ I'd just invoke the method instead of hardcoding `true`.
Similar for other browsers.

Also, I think UA-checking for specific browsers in a way bowser does is
harmful, you took Chrome & Opera into account but there are other Chromium
clones, what about them? It'd be better to detect Chromium instead of
specific browsers IMO.

**Comment by zenorocha** [comment]
@mzgol good point about skipping the original function on Firefox. Unfortunately on Chrome it [still needs to be hard coded](https://code.google.com/p/chromium/issues/detail?id=476508).

**Comment by zenorocha** [comment]
About UA-checking, bowser actually handles that pretty well. Just tested on Chrome Stable, Chrome Canary and Chromium.

**Comment by gked** [comment]
@JamesMGreene,@mzgol: You can contact me for any editing related stuff when it comes to MS Edge.
Commenting to one of the post above - Edge doesn't fire any prompts on execCommand(cut/copy) events.
--grisha
