### ISSUE TITLE
Zeroclipboard works, but I didn't install Flash. Why?

### ISSUE THREAD

**Issue by IonicaBizau** [zeroclipboard/zeroclipboard#582]
![image](https://cloud.githubusercontent.com/assets/2864371/8107018/e1225f98-104e-11e5-9fbf-149f5cf069ab.png)

I'm running *Chromium Version 43.0.2357.81 Ubuntu 15.04 (64-bit)* and I have just noticed that Zeroclipboard works fine, even I didn't install Flash. The only related thing is that I installed Google Chrome (which brings Flash Player), but I'm not sure if that's the reason.

The videos on Facebook don't work using Chromium (they need Flash).

`(typeof navigator.plugins == "undefined" || navigator.plugins.length == 0) ? !!(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")) : navigator.plugins["Shockwave Flash"]` is `undefined`.

Also, what I see is that it only works on GitHub -- `ZeroClipboard.version => 2.1.6`. The demo website outputs *error[name="flash-disabled"]: Flash is disabled or not installed. May also be attempting to run Flash in a sandboxed iframe, which is impossible.*.

So, my question is what's the black magic for copying things in clipboard without installing Flash?

Thanks! :four_leaf_clover:

**Comment by IonicaBizau** [comment]
Confirming it does **not** work in Firefox. Also, I saw #580.

**Comment by JamesMGreene** [comment]
GitHub has started opting into the native Clipboard API for applicable versions of Chrome. This change lives outside of ZeroClipboard for the time being.

**Comment by JamesMGreene** [comment]
Speaking of which, @jonrohan: any chance of getting a few relevant code snippets added to #580 and/or #171?

**Comment by IonicaBizau** [comment]
@JamesMGreene Awesome! :sparkles: 

@jonrohan I am also interested to see the minimal code to copy things in clipboard. 

Saw something in dev tools: 

> ![image](https://cloud.githubusercontent.com/assets/2864371/8107660/a077a39a-1053-11e5-8aaa-2b1a5b748fbb.png)

**Comment by jonrohan** [comment]
Here's what github does to enable copy to clipboard without flash. It's based on useragent sniffing and not feature detection, which is why it's not in ZC yet. https://gist.github.com/jonrohan/81085b119d16cdd7868a

**Comment by IonicaBizau** [comment]
@jonrohan Thanks a lot! :cake:

[Played](http://jsfiddle.net/s2ru1jxb/) a little with it. Learning something new everyday. :smile: :books:

**Comment by JamesMGreene** [comment]
@IonicaBizau: Here's a general overview on the feature (though I believe there is some misinformation about browser support (at least without permissions prompts): http://updates.html5rocks.com/2015/04/cut-and-copy-commands

**Comment by IonicaBizau** [comment]
@JamesMGreene Interesting! I have been searching this for years. :smile_cat:
