### ISSUE TITLE
movie not loaded ... right click on glued object

### ISSUE THREAD

**Issue by Madzohan** [zeroclipboard/zeroclipboard#583]
<button onclick="event.preventDefault(); generateUrlToObject(this);" type="button" class="btn btn-salad btn-sm inline share-link" data-url=""><span class="glyphicon glyphicon glyphicon-copy"></span> {% trans 'Share link' %}</button>
   
    ZeroClipboard.config( { moviePath: 'static/clipboard/ZeroClipboard.swf' } );
    client = new ZeroClipboard( $("button.share-link") );  // after it button.share-link unable to hover

    // anything below doesn't work
    client.on( 'load', function(client) {

        client.on( 'datarequested', function(client) {
            var text = $('#copy_this_text').text();
            client.setText(text);
        });

        // callback triggered on successful copying
        client.on( 'complete', function(client, args) {
            console.log("Text copied to clipboard: \n" + args.text );
        });
    });

    // In case of error - such as Flash not being available
    client.on( 'wrongflash noflash', function() {
        ZeroClipboard.destroy();
    } );

[26/Jun/2015 02:17:00]"GET /static/clipboard/ZeroClipboard.js HTTP/1.1" 304 0
[26/Jun/2015 02:17:01]"GET /static/clipboard/ZeroClipboard.swf?noCache=1435274221127 HTTP/1.1" 200 0

http://take.ms/7MVKu

What I am doing wrong?

**Comment by JamesMGreene** [comment]
You're using a very invalid mix of `v1.x` and `v2.x` APIs. Pleaas read the docs. Here are 2 examples to get you headed in the right direction:
[docs/instructions.md#examples](https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/instructions.md#examples)

**Comment by Madzohan** [comment]
ok I've recorded screencast ... using minimal example that you've provided (same problem) ... please check it http://take.ms/ZVKiY thanks

**Comment by Madzohan** [comment]
after tried "A More Complete Example" button steel is unable some time (boring 10 -15 seconds in localhost 0o) but after - it trigger 'error' with event:

    Object {type: "error", name: "flash-deactivated", target: null, relatedTarget: null, currentTarget: object#global-zeroclipboard-flash-bridge…}client: ZeroClipboardcurrentTarget: object#global-zeroclipboard-flash-bridgemessage: "Flash is too outdated for your browser and/or is configured as click-to-activate.↵This may also mean that the ZeroClipboard SWF object could not be loaded, so please check your `swfPath` configuration and/or network connectivity.↵May also be attempting to run Flash in a sandboxed iframe, which is impossible."minimumVersion: "11.0.0"name: "flash-deactivated"relatedTarget: nulltarget: nulltimeStamp: 1435300361862type: "error"version: "18.0.0"__proto__: Object 

flash version is 18 ... and  [26/Jun/2015 09:32:12]"GET /static/clipboard/ZeroClipboard.swf?noCache=1435300331861 HTTP/1.1" 200 0 ... so why  ZeroClipboard SWF object could not be loaded?

**Comment by Madzohan** [comment]
I've tried relocate ZeroClipboard.swf (it was in same directory with ZeroClipboard.js) ... to media and seted path to it

    ZeroClipboard.config( { swfPath: "/media/ZeroClipboard.swf" } );

    [26/Jun/2015 10:28:29]"GET /media/ZeroClipboard.swf?noCache=1435303708765 HTTP/1.1" 200 0

steel the same ... :(

Chrome 43.0.2357.130 (64-bit) , Safari 8.0.4 (10600.4.10.7)

**Comment by Madzohan** [comment]
window.prompt("Copy to clipboard: Ctrl+C, Enter", text); Rocks! :+1:

**Comment by asfaltboy** [comment]
I've had a similar issue, and found that by reinstalling flash plugin (despite already having 18,0,0,209 installed), the issue was resolved.

**Comment by vipulblurb** [comment]
Hello,

I have added below script for copy to clipboard its working in my local system but not working on live server.  
I also check SWF file path its a right.
Can you please help me asap what is wrong?

<script type="text/javascript">
jQuery(document).ready(function(){

    var clientTarget = new ZeroClipboard( jQuery(".copy-button"), {
        moviePath:"<?php echo get_template_directory_uri(); ?>/zeroclipboard-2.2.0/dist/ZeroClipboard.swf",
        //moviePath:"http://www.dealslands.co.uk/wp-content/themes/clipper1rakesh/zeroclipboard-2.2.0/dist/ZeroClipboard.swf",
        debug: false
    });
    clientTarget.on( "load", function(clientTarget)
    {
        clientTarget.on( "complete", function(clientTarget, args) {
            clientTarget.setText( args.text );
        } );
    } );
    clientTarget.on('aftercopy', function(event) {
        jQuery('#copy-button').addClass('copied-btn');	
        jQuery('.copy-button').html("<i class='fa fa-check'></i> Copied");
    });
    //jQuery( "#terms-conditions" ).accordion({ collapsible: true});
});
</script>

Thanks
