### ISSUE TITLE
Document the object returned by ZeroClipboard.state()

### ISSUE THREAD

**Issue by dandv** [zeroclipboard/zeroclipboard#590]
I was looking for a way to tell if ZeroClipboard is usable (i.e. Flash installed and a sufficient version, or possibly other prerequisites) and https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/api/ZeroClipboard.md#zeroclipboardstate seemed handy. Since it's undocumented, should it be considered private, or subject to change?

In particular, is `ZeroClipboard.state().flash.ready` a reliable way to decide whether to show a ZC UI or fall back? In essence, I'm trying to avoid setting a global flag on error and would prefer to use ZeroClipboard's internally tracked state.

**Comment by JamesMGreene** [comment]
Ideally, you would just rely on our events instead of tracking it yourself manually, e.g.

```js
var client = new ZeroClipboard($('.clip-button'));
client.on('ready', function(e) {
  // Flash is all good
});
client.on('error', function(e) {
  // Most of our "error" events are caused by Flash being unusable, though a few are not.
  // You could also check the Flash state based on the `ZeroClipboard.state().flash` object here,
  // if you wanted.
});
```


In the near-ish future, I intend to be supplying a new event (e.g. "fallback") that more concisely informs the downstream dev that Flash isn't viable without having to worry about tracking a whole bunch of potential error events. See #552 for more info on that.

**Comment by JamesMGreene** [comment]
> Since it's undocumented, should it be considered private, or subject to change?

It should generally be considered private, yes.



> In particular, is `ZeroClipboard.state().flash.ready` a reliable way to decide whether to show a ZC UI or fall back?

Privateness aside, yes, that particular property is the single indicator of Flash viability. Here's its basic value meanings:
 - `true` indicates that Flash should definitely be ready and viable
 - `false` indicates that Flash is definitely NOT viable
 - `null` indicates that we have not yet determined authoritatively whether Flash is viable or not yet. (Please wait and check again.)
