### ISSUE TITLE
Spacing of copied text not respected when using Chrome and Windows Notepad

### ISSUE THREAD

**Issue by thadseaver** [zeroclipboard/zeroclipboard#595]
This is a bit obscure because it only seems to happen when copying text in Chrome and pasting into Windows Notepad. When copying text from a textarea, the spacing of the pasted text gets messed up. This is not desirable because the copied text is Javascript code and I have specifically formatted the text to stay within the desired 80 character lines. If I manually select all the text and Ctrl+C (in other words, bypass ZeroClipboard altogether), the spacing is maintained as desired.

This issue does not appear in Firefox 39 or IE10, but does appear in Chrome 44.

If copied in Chrome and pasted into any other editor (I’ve tested Sublime Text, Dreamweaver, MS Word, Windows Wordpad, and Notepad++), the spacing is maintained as desired.

In the below example, the first array was copied/pasted using ZeroClipboard. Notice the spacing. The second array was copy/pasted without the use of ZeroClipboard. It has the correct spacing.

![](http://thadseaver.com/files/zc-example.jpg)

Can be tested at this site:
[http://array-ipsum.com](http://array-ipsum.com)

Thad

**Comment by JamesMGreene** [comment]
While this is technically a known issue (and very specific to Notepad only, for the record) that is [already documented](https://github.com/zeroclipboard/zeroclipboard/blob/9b061c1600c5cb486e7923d7c020480208d71c02/docs/instructions.md#windows), this has come up often enough now that I'm just going to address it in the code instead wholesale.  While Notepad seems to be the only application stupid enough to not correctly display `"\n"` without preceding `"\r"` characters, using Notepad is also a common use case and ensuring OS-compliant line ending is a reasonable expectation [despite Chrome's decision to _not_ provide the `"\r"` characters to us on Windows when getting the text value of such elements].

**Comment by thadseaver** [comment]
Sorry James, I read through the known issues before posting and don't know how that slipped past me. It's there plain as day.

**Comment by JamesMGreene** [comment]
No worries, fix will be arriving shortly... just finishing writing a few tests now. :+1:

**Comment by thadseaver** [comment]
Works perfect. Thank you!

**Comment by JamesMGreene** [comment]
Great. Thanks for testing it out, @thadseaver! :+1:

**Comment by shining01** [comment]
as discribed in bug #610 (which is a duplicate from this), notepad and in our erp-System (Billing Software) i have this problems. Thanks a lot!
