### ISSUE TITLE
IE Bug

### ISSUE THREAD

**Issue by YouriT** [zeroclipboard/zeroclipboard#597]
Hi,

I'm using ZeroClipboard v2.2.0, and I'm having some troubles with IE11 (only version tested for now), with a strange message saying that `e2 is undefined` in `_detectFlashSupport` function.

Is anyone having the same issue?

Cheers,

Youri

**Comment by JamesMGreene** [comment]
I cannot reproduce this in IE11 on Windows 7 using the demo page http://zeroclipboard.org/.

If anyone else is running into this (or if you still are, @YouriT), please let me know. Thanks!
