### ISSUE TITLE
Will this project die?

### ISSUE THREAD

**Issue by edpichler** [zeroclipboard/zeroclipboard#599]
Some great browsers are removing support to flash. Will 'copy to clipboard' feature possible to do without flash next years? I'm using the tool and a little bit worried about this.

**Comment by JamesMGreene** [comment]
We've been working with browser vendors to ensure that a similar functionality is available in browsers natively going forward.  Although its spec is still changing (and a bit tumultuous lately, it seems), the current version of it has already been [somewhat] implemented in IE 10+, Chrome 43+, Opera 29+, and in Firefox with a preference change.  Either way, like most DOM APIs, the API for the functionality is still pretty ugly, so I imagine ZeroClipboard will continue to exist to both (a) wrap the API to be more user friendly and (b) to continue to support Flash fallbacks in older browsers.

Keep an eye on #171.

**Comment by edpichler** [comment]
Excellent. Thank you.

On Fri, Aug 21, 2015 at 3:24 PM, James M. Greene <notifications@github.com>
wrote:

> Closed #599 <https://github.com/zeroclipboard/zeroclipboard/issues/599>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zeroclipboard/zeroclipboard/issues/599#event-389084982>
> .
>



-- 
"Onde cruzam seus talentos e paixões com as necessidades do mundo, lá
estará o seu lugar"

                  Aristóteles
