### ISSUE TITLE
seem not woking with jquery tabs

### ISSUE THREAD

**Issue by myselfgaurav** [zeroclipboard/zeroclipboard#601]
i used it in accordian but is does not work when i am in 2nd tab it still show data as expected from buttons of 1st tab see below url

http://timesharefeed.com/,

check 3tabs , cnd , web hosting and plugin 

but even on 2 tab it seems taking value of 1st tab , pls fix

**Comment by JamesMGreene** [comment]
This worked fine for me when I tested it just now.

**Comment by JamesMGreene** [comment]
Values in my clipboard after clicking various "copy" buttons in your tabs:

 - Tab 1
     - Button 1: MAXCDN123
 - Tab 2
     - Button 1: hgwp123
 - Tab 3
     - Button 1: enviracoupon
     - Button 2: deviseshort

**Comment by JamesMGreene** [comment]
Please provide more information if you'd like further assistance.

**Comment by JamesMGreene** [comment]
Closing for now due to lack of required information.

@myselfgaurav: Feel free to reopen this issue if you are still running into this problem and can provide more information.
