### ISSUE TITLE
show zeroclipboard button  on hover

### ISSUE THREAD

**Issue by tomalex0** [zeroclipboard/zeroclipboard#605]
Im trying to  show zeroclipboard button inside  element `A ` when `A` is hovered. But as i  hover the clipboard button  css hover on `A` stops working. Is it possible to fix  this using CSS itself?

**Comment by JamesMGreene** [comment]
Please read the [CSS Effects](https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/instructions.md#css-effects) section of the docs.
