### ISSUE TITLE
zero clipboard doesn't work with display:inline

### ISSUE THREAD

**Issue by kodjoe** [zeroclipboard/zeroclipboard#607]
Hello zeroclipboard doesn't work when display:inline is used. 
I've a page with slide up and down effect, who used display:block and display:inline to show/hide content.

when display:block is used, zero clipboard works perfectly, but when my content is visible with display:inline, zero clipboard copy nothing.

did you have an idea ?

Thank you

**Comment by jonrohan** [comment]
I would recommend using `display:inline-block` on the element. The nature of an inline element won't work well with the absolutely positioned elements. As inline elements can span multiple lines

**Comment by JamesMGreene** [comment]
Just for a little more background, `display:inline` elements also have the curious quality of NOT having an implicitly computed `height` or `width` value.  This makes them impossible to properly triangulate and overlay.

**Comment by kodjoe** [comment]
can you explain me in my page: http://500milligrammes.com/facticemagazine/final/0/
why only the third "copy link" works only if all panels are closed ?

**Comment by kodjoe** [comment]
the problem is resolved -> I'd to change position absolute by inherit on the query.zclip.js ;D

thanks mates
