### ISSUE TITLE
Support Named AMD

### ISSUE THREAD

**Issue by hhff** [zeroclipboard/zeroclipboard#611]
Super simple tweak to support Named AMD - thoughts?

``` js
  // ...snip...

  if (typeof define === "function") {
    if (define.amd) {
      define(function() {
        return ZeroClipboard;
      });
    } else {
      define('ZeroClipboard', function() {
        return ZeroClipboard;
      });
    }
  } else if (typeof module === "object" && module && typeof module.exports === "object" && module.exports) {
    module.exports = ZeroClipboard;
  } else {
    window.ZeroClipboard = ZeroClipboard;
  }
})(function() {
  return this || window;
}());
```

**Comment by JamesMGreene** [comment]
I'm not familiar with any library for AMD that falls into that camp. Can you provide more background on your request?

**Comment by JamesMGreene** [comment]
Offhand, it seems like you are suggesting the use of an AMDJS loader library that doesn't officially support the AMDJS API. Is that correct?

**Comment by hhff** [comment]
Yup!  Wanting to use this lib with Ember CLI & ES6 modules like so:

`import ZeroClipboard from 'ZeroClipboard';`

Their loader code is here: https://github.com/ember-cli/loader.js - it's super minimal and doesn't have `define.amd`, but regardless works to the spec.  

AMD supports an optional `module_id` - which is how the Ember CLI allows the lib to be referenced with ES6 modules.

Plenty of libs out there already do this.  [Dynamics.js is one of many](https://github.com/michaelvillar/dynamics.js/blob/master/src/dynamics.coffee#L1471)

**Comment by JamesMGreene** [comment]
That's a pretty loose API assumption to make but I suppose that is acceptable so long as no one else reports trouble from the changes.

**Comment by hhff** [comment]
> That's a pretty loose API assumption to make

I don't know what you mean by this?

**Comment by JamesMGreene** [comment]
@stefanpenner Can you either confirm that adding an alternate logic gate like this is the best way for a library to integrate into the Ember ecosystem, or, if not, advise @hhff upon the best practice in such a situation?  I'm unsure of this one.

**Comment by JamesMGreene** [comment]
Per my chat with @stefanpenner, he informed me that this should no longer be necessary (though it would've been at the time).

Now, you can do something like [this](https://github.com/ember-cli/ember-cli/blob/master/tests/fixtures/brocfile-tests/app-import-anonymous-amd/ember-cli-build.js) (via PR https://github.com/ember-cli/ember-cli/pull/5976) instead:

```js
app.import(
  'vendor/zeroclipboard.min.js',
  {
    using: [
      { transformation: 'amd',  as: 'zeroclipboard' }
    ],
    outputFile: '/assets/output.js'
  }
);
```

**Comment by JamesMGreene** [comment]
Does this fit your needs, @hhff?  If not, please let me know and we can reopen this.

**Comment by stefanpenner** [comment]
> outputFile: '/assets/output.js'

this can be omitted, as it will "join" the default vendor file.

**Comment by hhff** [comment]
whew!  Looks good - thanks @JamesMGreene & @stefanpenner !!
