### ISSUE TITLE
Zeroclipboard flash-deactivated error in frame

### ISSUE THREAD

**Issue by jrberlin** [zeroclipboard/zeroclipboard#612]
Hi !
I am trying to use ZeroClipboard 2.2.0 inside a frame in chrome, that is not sandboxed and I always get the following error:

"ZeroClipboard error of type "flash-deactivated": Flash is too outdated for your browser and/or is configured as click-to-activate.
This may also mean that the ZeroClipboard SWF object could not be loaded, so please check your `swfPath` configuration and/or network connectivity.
May also be attempting to run Flash in a sandboxed iframe, which is impossible."

Flash plugin version is 18 and it is fully enabled in Chrome, I checked the path to the movie and I can load it in the browser by copy pasting the configure URL.

the html is sth like this:

<-frameset cols="25%,*,25%">
  <-frame src="frame_a.htm">
  <-frame src="frame_b.htm">
  <-frame src="A">
<-/frameset>

All our logic and buttons are in the "A" frame, the swf file is located in a different folder than the library and when I load the app, I do use of the config method. I dont understand what can be the problem, any help is really appreciate.

Thanks a lot !!
Julian

**Comment by JamesMGreene** [comment]
Could you please create a small live webpage that serves as a reproducible test case for us?  Thanks!

**Comment by jrberlin** [comment]
Hi James
I will provide a small example as soon as I can ! thanks for the quick reply.

All the best,
Julian

**Comment by jrberlin** [comment]
Hi James,
I fixed my problem, I was using a different version of the swf file so I guess that was the cause of the problem ! thanks a lot ! very nice project !

Julian
