### ISSUE TITLE
New line feeds not copied

### ISSUE THREAD

**Issue by JoeyACS** [zeroclipboard/zeroclipboard#613]
on a windows 2012 server 64-bit server when I use the demo at http://zeroclipboard.org/ and enter multiple lines,e g.

Line1
Line2
Line3

and I click Copy to Clipboard....
then I start notepad and paste I end up with this data:
Line1LIne2Line3

**Comment by JamesMGreene** [comment]
Duplicate of #595. Already fixed in the current `master` branch but not yet released.
