### ISSUE TITLE
Question: how to add a class to the data-clipboard-target element?

### ISSUE THREAD

**Issue by migswd** [zeroclipboard/zeroclipboard#615]
I  would like to animate the data-clipboard-target element by adding a class when I click the copy button. So the user would understand that the copy to clipboard worked.  
But despite your amazing tutorials and instructions text I cannot find an example on this particular case.

**Comment by JamesMGreene** [comment]
So, the following is what I understand you are asking for.  If I'm mistaken, please help us clarify your needs.

**You want to:** add a `class` to an associated element [specified by the `data-clipboard-target` attribute on the clipped button/link/element] after a successful clipboard injection (copy).

If that's right, you could achieve this with something like the following code snippet (assumes you have a jQuery-esque `$` available but can easily be achieved without it):

```js
var client = new ZeroClipboard( $("button[data-clipboard-target]") );

client.on("error", function(e) {
  console.error("ZeroClipboard error event: " + JSON.stringify({ name: e.name, message: e.message }));
});

client.on("ready", function(e) {

  // START OF IMPORTANT PART
  client.on("aftercopy", function(e) {
    if (e.relatedTarget && ( e.success["text/plain"] || e.success["text/html"] )) {
      $(e.relatedTarget).addClass("copied");
    }
  });
  // END OF IMPORTANT PART

});
```

**Comment by migswd** [comment]
Perfect ! Thank you again for this great plugin.
