### ISSUE TITLE
Test failures on Windows: client/api.js unit tests - clipboard - `setRichText` works

### ISSUE THREAD

**Issue by hallvors** [zeroclipboard/zeroclipboard#616]
This test fails on Windows because of newline handling - the code does some newline fixing and the test doesn't expect this.

**Comment by JamesMGreene** [comment]
Ahh, good catch @hallvors.  Most of my ZeroClipboard development work was on Windows but I've been on Mac for the last year (during which I very recently added the newline handling for Windows).

**Comment by hallvors** [comment]
Want to take this? https://github.com/hallvors/zeroclipboard/commit/ffbdebdeb842ed1afe05b9bc7275d8d2e8bb4163

**Comment by hallvors** [comment]
Hm.. that breaks building with a  ```^ '_fixLineEndings' is not defined``` message from jshint:test. Not sure how this stuff works.

**Comment by JamesMGreene** [comment]
@hallvors: Just add `, _fixLineEndings` somewhere on the `/*global ...` comment on the very first line of that JS file.

**Comment by JamesMGreene** [comment]
Normally that kind of thing wouldn't be necessary but most of our unit tests are testing at the private level rather than the API level, so we actually expose all of the private methods.

**Comment by hallvors** [comment]
This PR will take care of it: https://github.com/zeroclipboard/zeroclipboard/pull/622

**Comment by JamesMGreene** [comment]
Fixed by #622
