### ISSUE TITLE
ZeroClipboard Not Working in Safari Version 7.1 (9537.85.10.17.1)

### ISSUE THREAD

**Issue by amolplay** [zeroclipboard/zeroclipboard#621]
I have used gem ZeroClipboard but it's Copy Event not working in Safari 7.1.

But It is working on Chrome Version 46.0.2490.86 (64-bit). 

Please provide the solution.

**Comment by JamesMGreene** [comment]
Please provide the output of running `console.log (JSON.stringify(ZeroClipboard.state(), null, 2))` in the Safari developer console.

**Comment by MickeyKay** [comment]
I'm experiencing this issue as well. Here's the output:

```
[Log] {
  "browser": {
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9",
    "platform": "MacIntel",
    "appName": "Netscape"
  },
  "flash": {
    "version": "0.0.0",
    "pluginType": "unknown",
    "disabled": true,
    "outdated": "",
    "sandboxed": false,
    "unavailable": null,
    "degraded": null,
    "deactivated": null,
    "overdue": null,
    "ready": false
  },
  "zeroclipboard": {
    "version": "2.2.0",
    "config": {
      "swfPath": "http://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.swf",
      "trustedDomains": [
        "localhost:8888"
      ],
      "cacheBust": true,
      "forceEnhancedClipboard": false,
      "flashLoadTimeout": 30000,
      "autoActivate": true,
      "bubbleEvents": true,
      "containerId": "global-zeroclipboard-html-bridge",
      "containerClass": "global-zeroclipboard-container",
      "swfObjectId": "global-zeroclipboard-flash-bridge",
      "hoverClass": "zeroclipboard-is-hover",
      "activeClass": "zeroclipboard-is-active",
      "forceHandCursor": false,
      "title": null,
      "zIndex": 999999999
    }
  }
}
```

**Comment by JamesMGreene** [comment]
You need to install and/or enable Flash Player for Safari and Firefox. Chrome has Flash built-in.

**Comment by vemv** [comment]
> You need to install and/or enable Flash Player for Safari and Firefox. Chrome has Flash built-in.

How is this a satisfactory answer?

Firefox (and now Safari) disable Flash by default. It should be prominently visible that ZC won't work out of the box for FF and Safari users.

For example the 'copy to clipboard' button from github.com (a notorious ZC user) just doesn't work for me.

**Comment by ahfarmer** [comment]
I think the documentation should be clear about this upfront.

FYI 'copy to clipboard' now works on GitHub in Safari without flash. I inspected the source and found a reference to `execCommand('copy')`. I suspect that GitHub now tries other means first and only uses ZeroClipboard as a fallback.

**Comment by miguelmota** [comment]
For Safari support I switched to clipboard.js

https://github.com/zenorocha/clipboard.js
