### ISSUE TITLE
Zeroclipboard + Bootstrap combination not working

### ISSUE THREAD

**Issue by behnampmdg3** [zeroclipboard/zeroclipboard#629]
Hi;

I am using Zeroclipboard but for some reason it doesn't work with bootstrap!

There are no errors in console, it just doesn't copy! I see it loads the flash and everything, but doesn't show the alert or copy!

I right click on the button, the flash player setting appears.

Can someone please help me find out why this isn't working?

This alert alert( "ZeroClipboard SWF is ready!" ); is not showing.

Here is the live code: http://webmoosh.com/garbage/test

Thanks

**Comment by JamesMGreene** [comment]
You are not hosting the ZeroClipboard SWF file on your site.
