### ISSUE TITLE
Use moviePath or swfPath in constructor?

### ISSUE THREAD

**Issue by WaveyMaple** [zeroclipboard/zeroclipboard#633]
My old code using v1.2.0-beta.4 used moviePath in the constructor of ZeroClipboard
```
<script type="text/javascript">
    var clip = new ZeroClipboard(document.getElementById("btnZero"),
{ moviePath: "ZeroClipboard/ZeroClipboard.swf"});
    clip.on('mouseover', function (client) {btnZero.src="Images/copy32hover.png";});
    clip.on('mouseout', function (client) {btnZero.src="Images/copy32.png";});
    clip.on('mousedown', function (client) {btnZero.src="Images/copy32down.png";});
    clip.on('mouseup', function (client) {btnZero.src="Images/copy32hover.png";});
</script>
```
however in the example I see it setting the swfPath attribute (although in a slightly different context through Config()).
https://github.com/zeroclipboard/ZeroClipboard/blob/master/docs/instructions.md

Which should be used?  I also see James' response here regarding moviePath
https://github.com/zeroclipboard/zeroclipboard/issues/238
mind you his post at the bottom here on 2014.Jan.20 seems to point to using swfPath:
https://github.com/zeroclipboard/zeroclipboard/issues/323

I am asking because, as I will put into another thread, I have upgraded to v2.2.0 and both swfPath and moviePath work on my Visual Studio Win7 development box, but does not work on the production server.  That is another issue.

**Comment by JamesMGreene** [comment]
In `v2.x`, you must use `swfPath`.  More info:  [`1.x-master`@docs/instructions.md#deprecations](https://github.com/zeroclipboard/zeroclipboard/blob/1.x-master/docs/instructions.md#deprecations)

Furthermore, however, if your "ZeroClipboard.swf" file (must be that exact name) is located in the same directory as your "ZeroClipboard.js" file (or whatever JS file contains the ZeroClipboard code), then you shouldn't even need to set it explicitly at all... ZeroClipboard will automatically set its dir path to match the JS file's dir path.
