### ISSUE TITLE
Upgrade from v1.2.0-beta.4 to v2.2.0 = partially working in Visual Studio, not working at all on Production

### ISSUE THREAD

**Issue by WaveyMaple** [zeroclipboard/zeroclipboard#634]
Hi there,

I was previously using ZeroClipboard v1.2.0-beta.4 (as it appeared in ZeroClipboard.js) and everything was great:
1. Runs on both my Windows 7 development box in an ASP.NET Visual Studio application, as well as on the live production Win 2012 64-bit server.  In both environments, right-clicking on my asp:ImageButton shows the Flash menu Settings/Global Settings/About...
2. Copies the data properly.
3. Changes the images based upon mouse movements.

`<script type="text/javascript">
    var clip = new ZeroClipboard(document.getElementById("btnZero"),
{ moviePath: "/ZeroClipboard/ZeroClipboard.swf"});
    clip.on('mouseover', function (client) {btnZero.src="Images/copy32hover.png";});
    clip.on('mouseout', function (client) {btnZero.src="Images/copy32.png";});
    clip.on('mousedown', function (client) {btnZero.src="Images/copy32down.png";});
    clip.on('mouseup', function (client) {btnZero.src="Images/copy32hover.png";});
</script>`

But after upgrading, I see very strange behaviour:
1. Seems to be there on both dev machine and production in terms of right-clicking and seeing the Flash menu.
2. But only copies the data on the dev machine.  Does not work at all on production.
3. And the images no longer change on either machine.

I don't know if the specification has changed since I was using such an older version in terms of point 3 or the previous points.  So far I have investigated down the path of the filepath of ZeroClipboard.swf (ref Issue #633) along with fully specifying the path, with/without 'http', using standard absolute root '/' or not (ref James' comment at bottom of Issue #323), etc. with no luck.  Any and all advice would be appreciated.

Not sure if this is relevant, but when I hover over the button when debugging in Chrome on my dev machine, I see that the <input> control I see the tooltip appear, and the class attribute change from being empty to 'zeroclipboard-is-hover' and then when I press the mouse down change to 'zeroclipboard-is-hover zeroclipboard-is-active'.

Oh, from James' queries on other posts, FYI if it matters, here is my machine:
https://aboutmybrowser.com/5r6RySw0
and when going to the Using Pepper Flash? test it returns true.

Thanks!

**Comment by JamesMGreene** [comment]
As is intended with Semantic Versioning, `v2.x` was a major breakage of the API from `v1.x`.  More info:  [`1.x-master`@docs/instructions.md#deprecations](https://github.com/zeroclipboard/zeroclipboard/blob/1.x-master/docs/instructions.md#deprecations)
