### ISSUE TITLE
ZeroClipboard auto loads, calling callDomLoadFunctions ensuring a 404 since I .config it in code

### ISSUE THREAD

**Issue by PandaWood** [zeroclipboard/zeroclipboard#642]
I can't see why this should be happening. Is it expected?

I explicitly call ZeroClibpboard.config in my own code.

But seemingly just by the js library being included, on DOM load, ZeroClipboard is loading, calling this callDomLoadFunctions() function and throwing a 404 in the console when the library isn't in the default place.
Ultimately ZeroClipboard works, because I configure it where the .swf actually is, but I don't want any auto-initialization and this 404

**Comment by JamesMGreene** [comment]
The function `callDomLoadFunctions` isn't a part of ZeroClipboard, nor is it used by it.  It is a part of the "swfobject" library.  Do you have any other Flash elements on your page that might be getting loaded via swfobject?
