### ISSUE TITLE
demo page cannot run on a local environment

### ISSUE THREAD

**Issue by maicWorkGithub** [zeroclipboard/zeroclipboard#643]
and i save all file of http://zeroclipboard.org/, still cannot work.
and i try **sample example** in [this page](https://github.com/zeroclipboard/zeroclipboard#simple-example), still cannot work. my browser is chrome 49, thanks for your help.

**Comment by maicWorkGithub** [comment]
here is my code
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <script src="ZeroClipboard.js"></script>
</head>
<body>
  <div id="text">sadsadsadewasdrfds</div>
  <button type="button" name="button" id="btn" data-clipboard-target='text' data-clipboard-text="Default clipboard text from attribute">click to capy</button>

</body>
</html>
<script>
  var btn = document.getElementById('btn');
  var cli = new ZeroClipboard(btn);
  cli.on('ready', function () {
    alert('ready')
    cli.on('aftercopy', function (e) {
      e.target.style.display="none";
      alert('copyd')
    })
  });
</script>
```

**Comment by JamesMGreene** [comment]
Do you have both the "ZeroClipboard.js" and "ZeroClipboard.swf" files on your local system in the same directory as this HTML file?

**Comment by JamesMGreene** [comment]
Also, does it work in any other browser?

**Comment by maicWorkGithub** [comment]
Yes, Firefox, IE11, Edge, Chrome, all this cannot work.

Even cannot click the button

**Comment by JamesMGreene** [comment]
Please be sure to read about the [Cross-Protocol Limitations](https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/instructions.md#cross-protocol-limitations) and [`file://` Protocol Limitations](https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/instructions.md#file-protocol-limitations) and ensure your local setup and hosting/browsing aren't falling into one of those situations.
