### ISSUE TITLE
 At the same time and sortable plug-in can not be replicated in chrome

### ISSUE THREAD

**Issue by splp** [zeroclipboard/zeroclipboard#644]
jQuery(function() {
		  var client = new ZeroClipboard($('.J_copy_clipboard_data'));
		  client.on('ready', function(event) {
		    client.on('copy', function(event) {
		      var txt = $(event.target).attr("url_copy");
		      	event.clipboardData.setData('text/plain', txt);
		    });
		  });

	// 拖拽
	$("#sortable").sortable({
		connectWith: ".dd-item",
		items: ".dd-item",
		opacity: 0.8,
		coneHelperSize: true,
		placeholder: 'sortable-box-placeholder round-all',
		forcePlaceholderSize: true,
		tolerance: "pointer"
	});
		});

**Comment by JamesMGreene** [comment]
Can you elaborate?  I have no idea what the issue that you are facing actually is based on your initial comment.

**Comment by splp** [comment]
I found the pr

**Comment by splp** [comment]
The problem is event bubbling
