### ISSUE TITLE
Improving XHTML Support by Escaping Ampersands in SWF URL

### ISSUE THREAD

**Issue by FuweiChin** [zeroclipboard/zeroclipboard#647]
Here is the error occured on Chrome:  
`ZeroClipboard.js:1216 Uncaught SyntaxError: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.`

As I'm an XHTML practitioner, consider the following code:

``` js
var swfUrl = _globalConfig.swfPath + _cacheBust(_globalConfig.swfPath, _globalConfig);
//+++begin fix
var escapeXML=function(){
    return String(s).replace(/["&'<>]/g, function(c){
        switch(c){
        case '\x22':return "&quot;";
        case '\x26':return "&amp;";
        case '\x27':return "&apos;";
        case '\x3C':return "&lt;";
        case '\x3E':return "&gt;";
        }
    });
};
if(document.documentElement.nodeName=="html"){//XHTML mode
    swfUrl=escapeXML(swfUrl);
}
//+++end fix
```

**Comment by JamesMGreene** [comment]
Makes sense, so long as it doesn't negatively impact the URL that is received on the Flash side.

It took me a minute to figure out what your `if` condition was actually checking, so that would definitely require better comments. 😄
