### ISSUE TITLE
data-clipboard-target only can copy .value or .textContent or .innerText

### ISSUE THREAD

**Issue by rainforyou** [zeroclipboard/zeroclipboard#652]
if i want to copy the html code,how can i do
code like this :
    
` <textarea id="fe_text" cols="50" rows="3"><b>123</b></textarea>
   <button id="d_clip_button" class="my_clip_button" title="Click me to copy to clipboard." data-clipboard-target="fe_text">Copy To Clipboard...</button>`

it seems that i can only get the  "123"  ,but i want to get   `<b>123</b>`

**Comment by JamesMGreene** [comment]
A `textarea` element only technically allows text nodes inside of it, so your use of an embedded `<b>` bold tag is technically incorrect.  The correct HTML for setting such an initial value would be `<textarea>&lt;b&gt;123&lt;/b&gt;</textarea>`.  That said, many of the browsers will be forgiving and try to correct that issue by either (a) ignoring those `<b>` tags or (b) automatically converting them into the HTML entities `&lt;` and `&gt;` that I mentioned above.

If I am understanding you correctly, it seems like what you want to do is to copy the unescaped contents of it as plain text.  For that, you would need to get a little more involved, e.g.

```js
var client = new ZeroClipboard( document.getElementById( 'd_clip_button' ) );

client.on( 'ready', function( event ) {
  client.on( 'copy', function( event ) {
    var rel = event.relatedTarget;  // the element specified by `data-clipboard-target`
    if ( rel ) {
      event.clipboardData.clearData();
      event.clipboardData.setData( 'text/plain', rel.value || rel.textContent || rel.innerText );
    }
  } );
} );

client.on( 'error', function(event) {
  // console.log( 'ZeroClipboard error of type "' + event.name + '": ' + event.message );
  ZeroClipboard.destroy();
} );
```

**Comment by JamesMGreene** [comment]
Please let me know if this does not resolve your problem.  Thanks!

**Comment by rainforyou** [comment]
thanks
