### ISSUE TITLE
cannot use on mobile?

### ISSUE THREAD

**Issue by douglasvegas** [zeroclipboard/zeroclipboard#659]
I can copy the text  on the PC,but it doesnt work on mobile...
How to make it works on mobile?

**Comment by Spocher** [comment]
Join us. On mobile devices is not working. Is it possible to do this?

**Comment by douglasvegas** [comment]
It seems it has no permission to do this.

**Comment by JamesMGreene** [comment]
ZeroClipboard as it stands today will only work if Flash is available. Once we get #171 and its corresponding PR taken care of, that will add some support for mobile browsers that support the HTML5 Clipboard API as well.

Closing as duplicate of #171. Please subscribe to that issue instead for updates.
