### ISSUE TITLE
Compile ZeroClipboard.as but not work

### ISSUE THREAD

**Issue by dandandancj** [zeroclipboard/zeroclipboard#660]
Hi, i use flex sdk to compile as to swf in my computer, but the swf file does not work at all.
even I did not change the as code. the as file version is 1.0.7.

**Comment by JamesMGreene** [comment]
I'm not going to offer support for the ZeroClipboard `v1.x` series anymore as they are extremely old and the API dramatically changed in `v2.x` (again, a long time ago). Sorry!
