### ISSUE TITLE
ZeroClipboard not working in Edge

### ISSUE THREAD

**Issue by twocold0451** [zeroclipboard/zeroclipboard#662]
even the demo page .
it shows 

> error[name="flash-disabled"]: Flash is disabled or not installed. May also be attempting to run Flash in a sandboxed iframe, which is impossible.

**Comment by merdacz** [comment]
Looks like you have Flash disabled on your browser. Click ... icon in the top right corner. Then Settings and View Advanced Settings. You should have Use Adobe Flash Player toggle there. Switch it on and recheck.

**Comment by JamesMGreene** [comment]
Thanks for fielding this one, @merdacz.

**Comment by trongbq** [comment]
Although I enabled Flash Player on Edge, I still got this error.

**Comment by Kully** [comment]
> Although I enabled Flash Player on Edge and verified on other sites, I still got this error when trying to use _ZeroClipboard_.

I agree.

@trongbq Still have issues with Zeroclipboard on Edge? What version of Zeroclipboard are you using?
