### ISSUE TITLE
bower install error due to description length

### ISSUE THREAD

**Issue by martincostello** [zeroclipboard/zeroclipboard#663]
I installed ZeroClipboard via bower in AppVeyor as part of a CI build and received this error:

```
zeroclipboard#2.2.0 invalid-meta The "description" is too long, the limit is 140 characters
```

The [description](https://github.com/zeroclipboard/zeroclipboard/blob/d88febee4d1f9e6d6a347978dae4c545fd48985f/bower.json#L3) should be shortened so it is at most 140 characters to resolve the error.

**Comment by JamesMGreene** [comment]
Seriously? Bah, what a silly change on their part.

Our description is literally 141 characters long, so we'll just have to drop the period at the end. 😖 

Thanks for letting us know!

**Comment by JamesMGreene** [comment]
This change will go out with the next release publication. Thanks!
