### ISSUE TITLE
getData method get  empty  object？

### ISSUE THREAD

**Issue by yumenglong** [zeroclipboard/zeroclipboard#664]
getData方法为什么只有在调用setData方法之后才能获取到值呢？

**Comment by JamesMGreene** [comment]
Given the rough translation:
> Why only after calling the method `setData` method in order to get the value of it?

You cannot use the `getData` method to access the Clipboard data as the browser will not grant you permissions to it in that way.  With the newer HTML5 Clipboard API, you can get access to it during a `paste` event (which must be triggered by the user initiating an actual paste action) but not at any other time.
