### ISSUE TITLE
Copy text with indirect formatting through CSS rules

### ISSUE THREAD

**Issue by kehu1991** [zeroclipboard/zeroclipboard#665]
Is it possible to copy text with formatting through CSS rules?

This works great:
`clipboard.setData("text/html", "<b>bold text</b>");`

However, copying this html will lose formats defined in CSS on class 'my-class':
`clipboard.setData("text/html", "<span class='my-class'>text</span>");`

If I select the content manually in browser and ctrl-C + ctrl-V, the content can be copied with CSS formatting. How does browser do this? Is it possible to achieve the same with zeroclipboard?

Appreciate your help!

**Comment by JamesMGreene** [comment]
AFAIK, there isn't any magical way to make this happen without extra effort on your part. For example, you could use a technique similar to the one in the [computed-style-to-inline-style](https://github.com/lukehorvat/computed-style-to-inline-style/blob/de61bb8d8a6a3e4dcfeb65360138a7c9d0c951a6/index.js) module to convert an element's computed CSS values into inline styles.
