### ISSUE TITLE
Copy Image to Clipboard not working for MS Word

### ISSUE THREAD

**Issue by rajatnarang94** [zeroclipboard/zeroclipboard#667]
I first converted image to a base64 string and then did this:
`clipboard.setData('text/html,'<img src = "img_string"/>')`
It works fine on LibreOffice writer and Google Docs but not working for MS Word. Something  is definitely getting copied to clipboard but word is not rendering it. Any idea how can I make it work?

**Comment by JamesMGreene** [comment]
Unfortunately, as far as I can see from various Google searches, MS Word's normal HTML cannot handle Data URI-based images.  However, supposedly if your document were an MHTML (MIME HTML) document instead, it _may_ work.

Not a very satisfactory reply, I know, but this one is in Microsoft's court to address.

**Comment by rajatnarang17** [comment]
Okay, Thank You!
