### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by cburgmer** [zeroclipboard/zeroclipboard#671]
The last release has been nearly 2 years back. There are fixes included we'd be happy to see.

**Comment by JamesMGreene** [comment]
Working on it when I can but my free time basically evaporated about 2 years ago. :cry:

There are a few more things I'm trying to cobble together before the next cut, see the "2.3.x" milestone.

**Comment by JamesMGreene** [comment]
ZeroClipboard `v2.3.0` is now built, tagged, released, and published. Enjoy, and thanks for waiting patiently!
