### ISSUE TITLE
chrome issue

### ISSUE THREAD

**Issue by zdig1** [zeroclipboard/zeroclipboard#673]
Hi, i get a little prblem for copying ... and i still dont know how to resolve ( newbie)
it is about this little script (virtual keybord) : [http://zdig01.freehostia.com/clavierarabe/ ](http://zdig01.freehostia.com/clavierarabe/ )

it work very nice with firefox but i cant copy with google chrome ! ( also opera)

chome refer this error 

>   Uncaught TypeError: ZeroClipboard is not a constructor

 //  main.js
`var client = new ZeroClipboard( document.getElementById("copy-button") );`

thx for help

**Comment by JamesMGreene** [comment]
If I open your site in Chrome 55 on Windows, the "copier" functionality appears to work just fine.

Can you please provide the output of running the following command in a browser dev console?

```js
console.log( JSON.stringify( ZeroClipboard.state() ) );
```

**Comment by JamesMGreene** [comment]
P.S. This is the state I get when I run that command in my working Chrome:

```json
{"browser":{"userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36","platform":"Win32","appName":"Netscape"},"flash":{"version":"23.0.0","pluginType":"pepper","disabled":false,"outdated":false,"sandboxed":false,"unavailable":false,"degraded":false,"deactivated":false,"overdue":false,"ready":true},"zeroclipboard":{"version":"2.2.0","config":{"swfPath":"http://zdig01.freehostia.com/clavierarabe/ZeroClipboard.swf","trustedDomains":["zdig01.freehostia.com"],"cacheBust":true,"forceEnhancedClipboard":false,"flashLoadTimeout":30000,"autoActivate":true,"bubbleEvents":true,"containerId":"global-zeroclipboard-html-bridge","containerClass":"global-zeroclipboard-container","swfObjectId":"global-zeroclipboard-flash-bridge","hoverClass":"zeroclipboard-is-hover","activeClass":"zeroclipboard-is-active","forceHandCursor":false,"title":null,"zIndex":999999999}}}
```

**Comment by zdig1** [comment]
me too i have th last chrome 55.0.x
when i type a text (keybord or mouse ) on the text area ..
then when i click the copier (copy) boutton ( 3rd one ) 
on firefox i get a box confirmation but not on chrome that is was copier to clipboard
any way after that when i try to past what supposed be copied
i dont get the correct text -> that mean it copy nothing

but when i test this with firefox it work like a charme i get the alert box and the past work perfectly

so when i tried to get more information i used inespector page of chrome and i see the message about Uncaught TypeError

i always thought that firefox is better than chrome and this is a confirmation :)

**Comment by JamesMGreene** [comment]
@zdig1: Please provide me with the info I requested or else I cannot help since I cannot reproduce the issue on my side currently.

**Comment by zdig1** [comment]
when i run the command 
`console.log( JSON.stringify( ZeroClipboard.state(), null, 2 ) );`

i get on chrome console
`Uncaught TypeError: ZeroClipboard.state is not a function
    at <anonymous>:1:44`

**Comment by JamesMGreene** [comment]
Seems like your ZeroClipboard script isn't even being loaded. What does `typeof ZeroClipboard` return?

**Comment by JamesMGreene** [comment]
@zdig1: Seems like your ZeroClipboard script isn't even being loaded.

 1. What does `typeof ZeroClipboard` return?
 2. Are there any other Error messages in the console?
 3. If you monitor the Network tab while loading the page/script, does it get downloaded into Chrome successfully?

**Comment by zdig1** [comment]
hi, it seem to b googl chome pb
today i get the new version 55.0.2883.87 and it work

thanks for all, and hope soon w get th 2.3 :)

**Comment by JamesMGreene** [comment]
Glad it's working now! Thanks for the update.
