### ISSUE TITLE
Why the button on github repo page doesn't need a flash object

### ISSUE THREAD

**Issue by Nomia** [zeroclipboard/zeroclipboard#679]
Hi, I'm going to use zeroclipboard in my another project. Thanks for your work.

But I've got a problem. The flash element will be on top of my "copy" button which will cause my "copy" button hide, because `onmouseout` or `onmouseleave` will make my "copy" button disappear.

I've double checked that the copy button on github repo page doesn't seem to use flash.
I right click on the github copy button, it's a normal context menu instead of a flash context menu.
![image](https://cloud.githubusercontent.com/assets/1707818/25178827/064e1b34-253a-11e7-8ab5-0a2afe1a3367.png)

And I cannot find any flash object element on the github page.
What trick did github use to not let the flash cover the copy button?

**Comment by JamesMGreene** [comment]
They utilize the HTML Clipboard API support in modern browsers first, if available, and fallback to ZeroClipboard.

See  #171 and PR #650 for more info.

**Comment by Nomia** [comment]
thanks.
