### ISSUE TITLE
not working in chrome 

### ISSUE THREAD

**Issue by yudehai0204** [zeroclipboard/zeroclipboard#690]
not working in chrome

**Comment by yudehai0204** [comment]
error[name="flash-disabled"]: Flash is disabled or not installed

**Comment by joy-yi0905** [comment]
By default, flash is disabled in chrome, and you must open it manually from [here](https://support.google.com/chrome/answer/6258784?visit_id=1-636478297969295225-3186222264&p=ib_blocked_plugin&rd=3)!
