### ISSUE TITLE
Unable to keep format as it is while copying

### ISSUE THREAD

**Issue by Kumar2k17** [zeroclipboard/zeroclipboard#691]
I have below code. But the problem is, when i try to copy the text, format getting disturbed. Please help me to get this fixed. For example, the same spacing lines are not getting copied, instead plain format is coming without spacing, next line etc.

code:
<link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'> 

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<script>
function copyToClipboard(element) {
  var $temp = $("<input>");
  $("body").append($temp);
  $temp.val($(element).text()).select();
  document.execCommand("copy");
  $temp.remove();
  alert("Text Copied");
}

</script>

<center> <textarea id="p1" cols="60" rows="13">

Hello Team,

Thank you for your Email.

You can follow below steps to fix the issue. You can also try below link for reference.

https://www.w3schools.com/css/default.asp

Note: Please use “Reply to All” while replying to this mail, so that my team can respond in my absence
 
Best Regards,
Kumar
Technology Services, Enterprise Group 
 
Please use this portal to view all your support case details
Website : http://www.google.co.in
</textarea>

<textarea id="p2" cols="60" rows="13">Hi,

Welcome to Tech world

please read all documents carefully

Regards,
XXXXXXX
Mobie:XXXX

</textarea>

<textarea id="p3" cols="60" rows="13">Hi,

Welcome to Tech world

please read all documents carefully

Regards,
XXXXXXX
Mobie:XXXX

</textarea></br>

<button onclick="copyToClipboard('#p1')">Firt box</button>
<button onclick="copyToClipboard('#p2')">second box</button>
 <button onclick="copyToClipboard('#p3')">Third Box</button> 

<br/><br/><input class="textBox" type="text" id="" placeholder="..TEST it here..;)" />
</center>

**Comment by JamesMGreene** [comment]
The code sample you gave is using pure browser DOM API code, it is not using ZeroClipboard at all.
