### ISSUE TITLE
Demo page not work but github copy clone url does?

### ISSUE THREAD

**Issue by deanorderly** [zeroclipboard/zeroclipboard#697]
I am confused.  I thought github.com was using the same zeroclipboard?  The demo linked does not work for me while the github copy/paste of the clone url works just fine.  Is there something wrong with the demo that github.com is doing correct?

**Comment by JamesMGreene** [comment]
GitHub has updated to use the [HTML Clipboard API 📋](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) that we helped get standardized. GitHub no longer needs to use ZeroClipboard as their browser support levels are limited to modern browser versions that all have the Clipboard API available.

If you are in a similar browser support level situation but still want a lightweight wrapper for the new Clipboard API, using [clipboard.js](https://clipboardjs.com) seems like your best option.
